const mongoose=require("mongoose")
const unitSchema=new mongoose.Schema({
    propertyId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Properties",
        required:true
    },
    unitNumber:{
        type:Number,
        require:true
    },
    monthlyRent:{
        type:Number,
        require:true
    },
    status:{
        type:String,
        enum:["vacant","occupied"],
        default:'vacant'
    },
    tenantId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Tenants",
        default:null
    }
},
{
    createdAt:true
}
)
module.exports=mongoose.model("units",unitSchema)